### ISSUE TITLE
SetMaskSize不会更改生成的背景图的遮罩尺寸

### ISSUE THREAD

**Issue by nicliuqi** [wangzmgit/jigsaw#1]
在jigsaw.go第162行中，maskFile通过路径读取图片，导致了如题的问题

**Comment by wangzmgit** [comment]
使用SetMaskSize只是用来获取遮罩图的尺寸，设置遮罩图尺寸后可以切割出与设置大小相同的小图。生成的背景图还是原来遮罩的大小

**Comment by nicliuqi** [comment]
btw，请教下遮罩图是否必须是正方形，可否换成其他的不规则图形

**Comment by wangzmgit** [comment]
只能是正方形的

**Comment by nicliuqi** [comment]
好的，感谢回答
